#!/usr/bin/env python3
"""
Privvy Database CLI Tool
Manage your database schema with ease - Inspired by Prisma!

Commands:
  init      Create a new schema.pv file
  migrate   Run migrations (create tables)
  push      Push schema changes to database
  seed      Seed the database with test data
  studio    Open database browser (coming soon)
  reset     Reset database (drop all tables)
"""

import sys
import os
import subprocess
from pathlib import Path

VERSION = "0.1.0"

# ANSI color codes for pretty output
class Colors:
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BOLD = '\033[1m'
    END = '\033[0m'

def print_banner():
    print(f"{Colors.BLUE}{Colors.BOLD}")
    print("╔═══════════════════════════════════════╗")
    print("║     Privvy Database CLI v" + VERSION + "        ║")
    print("║   The Easiest Backend Database Tool  ║")
    print("╚═══════════════════════════════════════╝")
    print(f"{Colors.END}")

def print_success(msg):
    print(f"{Colors.GREEN}✅ {msg}{Colors.END}")

def print_error(msg):
    print(f"{Colors.RED}❌ {msg}{Colors.END}")

def print_info(msg):
    print(f"{Colors.BLUE}ℹ️  {msg}{Colors.END}")

def print_warning(msg):
    print(f"{Colors.YELLOW}⚠️  {msg}{Colors.END}")

def cmd_init():
    """Create a new schema.pv file"""
    print_info("Creating schema.pv file...")
    
    if os.path.exists("schema.pv"):
        print_warning("schema.pv already exists!")
        response = input("Overwrite? (y/n): ")
        if response.lower() != 'y':
            print("Cancelled.")
            return
    
    schema_template = '''// schema.pv - Define your database models
// Generated by Privvy Database CLI

print("Loading database schema...")

// Example User Model
let User = Model("users", dict([
    "id", "INTEGER PRIMARY KEY AUTOINCREMENT",
    "username", "TEXT UNIQUE NOT NULL",
    "email", "TEXT UNIQUE NOT NULL",
    "password", "TEXT NOT NULL",
    "created_at", "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
]))

// Example Post Model
let Post = Model("posts", dict([
    "id", "INTEGER PRIMARY KEY AUTOINCREMENT",
    "user_id", "INTEGER NOT NULL",
    "title", "TEXT NOT NULL",
    "content", "TEXT",
    "published", "INTEGER DEFAULT 0",
    "created_at", "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
]))

// Add more models here...

print("✅ Schema loaded!")
print("   Models: User, Post")
'''
    
    with open("schema.pv", "w") as f:
        f.write(schema_template)
    
    print_success("Created schema.pv")
    print_info("Edit schema.pv to define your models")
    print_info("Then run: privvy-db migrate")

def cmd_migrate():
    """Run migrations - create tables from schema.pv"""
    print_info("Running migrations...")
    
    if not os.path.exists("schema.pv"):
        print_error("schema.pv not found!")
        print_info("Run 'privvy-db init' first")
        return
    
    # Check for database config
    db_url = os.environ.get("DATABASE_URL")
    if not db_url:
        # Default to SQLite
        db_url = "app.db"
        print_info(f"Using default database: {db_url}")
    
    # Create migrate.pv script
    migrate_script = f'''// Auto-generated migration script
let db = Database("{db_url}")
print("Connecting to database...")

// Load schema
// (In a real implementation, we'd parse schema.pv)
// For now, you need to manually call .migrate() on each model

print("✅ Migration complete!")
db.close()
'''
    
    with open(".migrate.pv", "w") as f:
        f.write(migrate_script)
    
    # Create a helper migration script
    migration_helper = f'''// Migration Helper
// Load your schema and run migrations

let db = Database("{db_url}")

// Load schema models
// (Copy your models from schema.pv or import them)

// Example: Uncomment and modify for your models
// User.migrate(db)
// Post.migrate(db)

print("✅ Migrations complete!")
db.close()
'''
    
    with open("migrate.pv", "w") as f:
        f.write(migration_helper)
    
    print_success("Created migrate.pv")
    print_info("Edit migrate.pv to add your models, then run:")
    print(f"{Colors.BOLD}    python3 privvy.py migrate.pv{Colors.END}")

def cmd_push():
    """Push schema to database"""
    print_info("Pushing schema to database...")
    
    if not os.path.exists("schema.pv"):
        print_error("schema.pv not found!")
        return
    
    print_info("Creating migration script...")
    
    # This would parse schema.pv and generate migration code
    # For now, provide instructions
    print_warning("Push functionality coming soon!")
    print_info("For now, use 'privvy-db migrate' to create tables")

def cmd_seed():
    """Seed database with test data"""
    print_info("Seeding database...")
    
    if not os.path.exists("seed.pv"):
        print_warning("seed.pv not found. Creating template...")
        
        seed_template = '''// seed.pv - Database seeding script
print("Seeding database...")

let db = Database("app.db")

// Load your models from schema.pv

// Example seed data
// let user1 = dict(["username", "alice", "email", "alice@example.com", "password", "hashed"])
// User.create(db, user1)

print("✅ Seeding complete!")
db.close()
'''
        
        with open("seed.pv", "w") as f:
            f.write(seed_template)
        
        print_success("Created seed.pv template")
        print_info("Edit seed.pv and run: privvy-db seed")
        return
    
    # Run seed script
    result = subprocess.run(["python3", "privvy.py", "seed.pv"])
    if result.returncode == 0:
        print_success("Database seeded!")
    else:
        print_error("Seeding failed")

def cmd_reset():
    """Reset database"""
    print_warning("This will DELETE all data!")
    response = input("Are you sure? Type 'yes' to confirm: ")
    
    if response != "yes":
        print("Cancelled.")
        return
    
    print_info("Resetting database...")
    
    # Create reset script
    reset_script = '''// Reset database
let db = Database("app.db")
print("Dropping all tables...")

// Load your models and drop them
// Example:
// User.drop(db)
// Post.drop(db)

print("✅ Database reset!")
print("Run migrations to recreate tables: privvy-db migrate")
db.close()
'''
    
    with open("reset.pv", "w") as f:
        f.write(reset_script)
    
    print_success("Created reset.pv")
    print_info("Edit reset.pv to add your models, then run:")
    print(f"{Colors.BOLD}    python3 privvy.py reset.pv{Colors.END}")

def cmd_studio():
    """Open database browser"""
    print_info("Database Studio coming soon!")
    print_info("For now, use a tool like DB Browser for SQLite")

def cmd_help():
    """Show help"""
    print(f"""
{Colors.BOLD}Usage:{Colors.END}
  privvy-db <command>

{Colors.BOLD}Commands:{Colors.END}
  {Colors.BLUE}init{Colors.END}      Create a new schema.pv file
  {Colors.BLUE}migrate{Colors.END}   Run migrations (create tables)
  {Colors.BLUE}push{Colors.END}      Push schema changes to database
  {Colors.BLUE}seed{Colors.END}      Seed database with test data
  {Colors.BLUE}reset{Colors.END}     Reset database (drop all tables)
  {Colors.BLUE}studio{Colors.END}    Open database browser (coming soon)
  {Colors.BLUE}help{Colors.END}      Show this help message

{Colors.BOLD}Examples:{Colors.END}
  privvy-db init         # Create schema.pv
  privvy-db migrate      # Create tables
  privvy-db seed         # Add test data

{Colors.BOLD}Environment Variables:{Colors.END}
  DATABASE_URL           Database connection string
                         Default: app.db (SQLite)

{Colors.BOLD}Learn More:{Colors.END}
  https://github.com/yourname/privvy
    """)

def main():
    print_banner()
    
    if len(sys.argv) < 2:
        cmd_help()
        return
    
    command = sys.argv[1]
    
    commands = {
        'init': cmd_init,
        'migrate': cmd_migrate,
        'push': cmd_push,
        'seed': cmd_seed,
        'reset': cmd_reset,
        'studio': cmd_studio,
        'help': cmd_help,
        '--help': cmd_help,
        '-h': cmd_help,
    }
    
    if command in commands:
        commands[command]()
    else:
        print_error(f"Unknown command: {command}")
        print_info("Run 'privvy-db help' for usage")

if __name__ == "__main__":
    main()

